### ISSUE TITLE
atom-build-sbt windows EOL

### ISSUE THREAD

**Issue by ghost1face** [jamesward/atom-build-sbt#4]
Setting up atom-build-sbt and was having problems building my single file test Scala app.  The problem I kept getting was 'No Active Targets'.  

Pulling up the debugger tools I see that when splitting the sbt output by os.EOL on windows the command list/targets aren't mapped.  If you change os.EOL to \n or probably better option for cross platform /\r?\n|\n/  everything runs fine.

I guess the issue really is sbt outputting standard (not windows standard) line endings on a windows machine.  But this should make it work cross platform. What do you think?

**Comment by jamesward** [comment]
Thanks for reporting the issue!  Check https://github.com/jamesward/atom-build-sbt/pull/5 to see if that is what you are proposing.

**Comment by ghost1face** [comment]
Yes! That should work 👍

**Comment by jamesward** [comment]
This has been released as `0.6.0` - let me know if it works.

**Comment by ghost1face** [comment]
Tested with latest release, works great.  Thanks
